"""Planning a push: which folders become which repository, and what it says."""

from __future__ import annotations

from pathlib import Path

from systemone.discover import Candidate, discover
from systemone.publish import home_mentions, merge, model_card, releases


def snake(workspace: Path) -> list[Candidate]:
    return [c for c in discover(workspace) if c.name == "snake-balanced"]


def test_a_single_model_sits_at_the_top_of_its_repository(workspace: Path) -> None:
    [release] = releases(snake(workspace)[:1])
    assert [part.folder for part in release.parts] == [""]
    assert release.folders == []


def test_a_single_model_can_be_given_a_folder(workspace: Path) -> None:
    [release] = releases(snake(workspace)[:1], "mlx/")
    assert release.folders == ["mlx"]


def test_variants_share_one_repository_a_folder_each(workspace: Path) -> None:
    [release] = releases(snake(workspace))
    assert release.name == "snake-balanced"
    assert release.folders == ["mlx", "coreml", "onnx-int8"]


def test_models_with_different_names_are_separate_repositories(workspace: Path) -> None:
    assert [r.name for r in releases(discover(workspace))] == ["guard", "snake-balanced"]


def test_clashing_variant_names_are_made_unique(workspace: Path) -> None:
    [run] = [c for c in discover(workspace) if c.kind == "laya-run" and c.name == "snake-balanced"]
    [release] = releases([run, run])
    assert release.folders == ["mlx", "mlx-2"]


def test_the_checkpoint_speaks_for_the_model(workspace: Path) -> None:
    [release] = releases(snake(workspace))
    found = merge(release.parts)

    assert found.evaluation["decision_accuracy"] == 0.9883
    assert found.details["base_metrics"]["accuracy"] == 0.158
    assert found.framework == "mlx, coreml, onnx"
    assert {"laya", "mlx", "coreml", "onnx", "int8"} <= set(found.tags)
    assert found.readme is not None and found.readme.startswith("# Snake")


def test_a_written_card_is_used_as_it_is(workspace: Path) -> None:
    [release] = releases(snake(workspace))
    release.namespace = "me"
    text, generated = model_card(release, merge(release.parts))
    assert not generated
    assert text.startswith("# Snake · balanced")


def test_a_model_without_a_card_gets_one_from_its_evaluation(workspace: Path) -> None:
    [release] = releases([c for c in discover(workspace) if c.name == "guard"])
    release.namespace = "me"
    text, generated = model_card(release, merge(release.parts))

    assert generated
    assert text.startswith("# Guard\n")
    assert "| Decision accuracy | **95.7%** |" in text
    assert "systemone pull me/guard\n" in text
    assert '"type": "noul"' in text
    assert "Generated by `systemone push`" in text


def test_a_generated_card_lists_variants_and_how_to_load_one(workspace: Path) -> None:
    candidates = snake(workspace)
    for candidate in candidates:
        readme = candidate.path / "README.md"
        if readme.exists():
            readme.unlink()
    [release] = releases(candidates)
    release.namespace = "me"
    text, generated = model_card(release, merge(release.parts))

    assert generated
    assert "| `onnx-int8/` | ONNX int8 |" in text
    assert "| `coreml/` | Core ML |" in text
    assert "systemone pull me/snake-balanced --variant mlx" in text
    assert 'snapshot_download("me/snake-balanced", variant="mlx") / "mlx"' in text
    assert "| Decision accuracy | 15.8% | **98.8%** [97.6%–99.4%] |" in text


def test_files_naming_the_home_folder_are_reported(workspace: Path, tmp_path: Path) -> None:
    [release] = releases(snake(workspace))
    assert home_mentions(release.parts, tmp_path / "home") == ["mlx/laya_finetune.json"]
    assert home_mentions(release.parts, tmp_path / "elsewhere") == []
